return {
  --   'nvim-neo-tree/neo-tree.nvim',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-tree/nvim-web-devicons',
  --     'MunifTanjim/nui.nvim',
  --   },
  --   event = 'VeryLazy',
  --   keys = {
  --     { '<leader><leader>', ':Neotree source=buffers reveal=true<CR>', silent = true, desc = 'Buffer Explorer' },
  --     { '<down>', ':Neotree toggle float<CR>', silent = true, desc = 'Float File Explorer' },
  --     { '<left>', ':Neotree position=left reveal=true<CR>', silent = true, desc = 'Open File Explorer' },
  --     { '<leader><left>', ':Neotree action=close<CR>', silent = true, desc = 'Close File Explorer' },
  --   },
  --   config = function()
  --     require('neo-tree').setup {
  --       close_if_last_window = true,
  --       popup_border_style = 'single',
  --       enable_git_status = true,
  --       enable_modified_markers = true,
  --       enable_diagnostics = true,
  --       sort_case_insensitive = true,
  --       default_component_configs = {
  --         indent = {
  --           with_markers = true,
  --           with_expanders = true,
  --         },
  --         modified = {
  --           symbol = ' ',
  --           highlight = 'NeoTreeModified',
  --         },
  --         icon = {
  --           folder_closed = '',
  --           folder_open = '',
  --           folder_empty = '',
  --           folder_empty_open = '',
  --         },
  --         git_status = {
  --           symbols = {
  --             -- Change type
  --             added = '',
  --             deleted = '',
  --             modified = '',
  --             renamed = '',
  --             -- Status type
  --             untracked = '',
  --             ignored = '',
  --             unstaged = '',
  --             staged = '',
  --             conflict = '',
  --           },
  --         },
  --       },
  --       window = {
  --         position = 'float',
  --         width = 35,
  --       },
  --       filesystem = {
  --         use_libuv_file_watcher = true,
  --         hijack_netrw_behavior = 'open_default',
  --         filtered_items = {
  --           hide_dotfiles = false,
  --           hide_gitignored = false,
  --           hide_by_name = {},
  --           never_show = {},
  --         },
  --       },
  --       source_selector = {
  --         winbar = false,
  --         sources = {
  --           { source = 'filesystem', display_name = '   Files ' },
  --           { source = 'buffers', display_name = '   Bufs ' },
  --           { source = 'git_status', display_name = '   Git ' },
  --         },
  --       },
  --       event_handlers = {},
  --     }
  --   end,
}
