format = """
$directory\
[](fg:#003319 bg:#006633)\
$git_branch\
$git_status\
[](fg:#006633 bg:#00994d)\
$python\
$nodejs\
$golang\
[](fg:#00994d bg:#00cc66)\
$time\
[](fg:#00cc66 bg:#00fd6f)\
$cmd_duration\
[](fg:#00fd6f)\
\n$character"""


# good bg colour: #003319

[directory]
style = "fg:#00ff7f bg:#003319"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#006633"
format = '[[ $symbol $branch ](fg:#00ff7f bg:#006633)]($style)'

[git_status]
style = "bg:#006633"
format = '[[($all_status$ahead_behind )](fg:#00ff7f bg:#006633)]($style)'

[python]
symbol = ""
style = "bg:#00994d"
format = '[[ $symbol ($version) ](fg:#00ff7f bg:#00994d)]($style)'

[nodejs]
symbol = ""
style = "bg:#00994d"
format = '[[ $symbol ($version) ](fg:#00ff7f bg:#00994d)]($style)'

[rust]
symbol = ""
style = "bg:#00994d"
format = '[[ $symbol ($version) ](fg:#00ff7f bg:#00994d)]($style)'

[golang]
symbol = ""
style = "bg:#00994d"
format = '[[ $symbol ($version) ](fg:#00ff7f bg:#00994d)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:#00cc66"
format = '[[ 󱑆 $time ](fg:#d7ede1 bg:#00cc66)]($style)'

[cmd_duration]
min_time = 1  # milliseconds
style = "bold yellow"
format = '[[ $duration ](fg:#ffffff bg:#00fd6f)]($style)'
disabled = false
