"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$cpp\
$golang\
$lua\
$nodejs\
$python\
$rust\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:#00cc00"
format = "[ $path ]($style)"

[character]
success_symbol ='[❯](fg:#00cc00)'
error_symbol = '[❯](red)'
vimcmd_symbol = '[❯](fg:#00cc00)'

[git_branch]
symbol = ""
style = "fg:#00cc00"
format = "| [$symbol]($style) $branch"

[git_status]
conflicted = "X"
untracked = "?"
modified = "~"
staged = "+"
renamed = "R"
deleted = "-"
stashed = "≡"
style = "fg:#00cc00"
format = " ($conflicted$untracked$modified$staged$renamed$deleted)($ahead_behind$stashed) "

[cmd_duration]
style = "yellow"
format = "| [$duration]($style)"

[python]
symbol = " "
style = "fg:#00cc00"
format = '| [$symbol]($style) ($virtualenv $version) '

[nodejs]
symbol = ""
style = "fg:#00cc00"
format = '| [$symbol ($version) ]($style) '

[rust]
symbol = ""
style = "fg:#00cc00"
format = '| [$symbol ($version) ]($style) '

[golang]
symbol = ""
style = "fg:#00cc00"
format = '| [$symbol ($version) ]($style) '

[cpp]
symbol = " "
style = "fg:#00cc00"
format = '| [$symbol ($version) ]($style) '

[lua]
symbol = " "
style = "fg:#00cc00"
format = '| [$symbol ($version) ]($style) '
