"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$cpp\
$haskell\
$java\
$kotlin\
$lua\
$zig\
$gradle\
$cmd_duration\
$custom\
$line_break\
$character\
"""

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:#01a2fb"
format = "[ $path ]($style)"

[character]
success_symbol ='[\$](fg:#01a2fb)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[\$](fg:#01a2fb)'

[git_branch]
symbol = ""
style = "fg:#01a2fb"
format = "| [$symbol]($style) main"

[git_status]
conflicted = "X"
untracked = "?"
modified = "~"
staged = "+"
renamed = "R"
deleted = "-"
stashed = "≡"
style = "fg:#01a2fb"
format = " ($conflicted$untracked$modified$staged$renamed$deleted)($ahead_behind$stashed) "

[cmd_duration]
style = "yellow"
format = "[$duration]($style) "

[python]
symbol = " "
style = "fg:#01a2fb"
format = '| [$symbol]($style) ($virtualenv $version)'

[nodejs]
symbol = ""
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[php]
symbol = ""
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[memory_usage]
symbol = "󰍛 "
style = "fg:#01a2fb"
format = '| [$symbol ($version) ]($style)'

[os.symbols]
Android = " "
Linux = " "
Macos = " "
Ubuntu = " "
Windows = "󰍲 "
